language: java
jdk:
- openjdk8
script:
  - mvn clean verify -Ddriver=chrome
after_failure:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report
  - echo "Build was failed"
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report
  - echo "Build was successful - travis test result $TRAVIS_TEST_RESULT"
after_script:
  - ls -la
  - echo "Script finished"
