language: java
script:
  - mvn clean verify -Ddriver=chrome
  - jdk_switcher use openjdk8
after_failure:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report
